#!/bin/bash
#SBATCH --partition=gpu-a100-80gb
#SBATCH --gres=gpu:a100_80gb:1
#SBATCH --time=00:10:00
#SBATCH --nodes=1

# load
# module load trytonp/cmdstan/2.34.1
# module load trytonp/mpi/openmpi3/3.1.4-gcc-system

# Setup OpenCL linker path
mkdir -p ~/lib_opencl_fix
ln -sf /usr/lib64/libOpenCL.so.1 ~/lib_opencl_fix/libOpenCL.so

export OPENCL_LIB_PATH=~/lib_opencl_fix
export LDFLAGS="-L${OPENCL_LIB_PATH}"
export LD_LIBRARY_PATH="${OPENCL_LIB_PATH}:$LD_LIBRARY_PATH"

#export STAN_THREADS=true
export CMDSTAN_MODEL_NAME="mod9"
export MODEL_SRC_DIR="/users/project1/pt01268/izo"

export CMDSTAN_DIR=~/cmdstan/2.34.1
cd $CMDSTAN_DIR

# Ensure CmdStan is built with OpenCL
make OPENCL=1 STAN_OPENCL=TRUE

# build/compile
[ -f ${MODEL_SRC_DIR}/${CMDSTAN_MODEL_NAME} ] && echo "Model " ${CMDSTAN_MODEL_NAME} " exists." || make STANCFLAGS=--O1 STAN_OPENCL=TRUE OPENCL_PLATFORM_ID=0 OPENCL_DEVICE_ID=0 ${MODEL_SRC_DIR}/${CMDSTAN_MODEL_NAME}

wait
