#!/bin/bash -l

#SBATCH --job-name=cmdstan_conda
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -p test
#SBATCH --time=00:15:00
#SBATCH --mem=2gb
#SBATCH --array=1%1 

# Załadowanie modułu
module load tryton/cmdstan/2.30.1-conda

export STAN_THREADS=false

# Nazwa modelu
export CMDSTAN_MODEL_NAME="hplc-qsrr-izo-diss-gp"

# Katalog z modelem (czyli gdzie się on znajduje)
export MODEL_SRC_DIR=${PWD}
cd ${MODEL_SRC_DIR}

# Budowanie modelu
[ -f ${CMDSTAN_MODEL_NAME} ] && echo "Model "${CMDSTAN_MODEL_NAME}" istnieje." || cmdstan_model ${CMDSTAN_MODEL_NAME}

wait
