#!/bin/bash -l

#SBATCH --job-name=cmdstan_conda
#SBATCH -N 1
#SBATCH -n 48
#SBATCH -p test
#SBATCH --time=00:15:00
#SBATCH --mem=64gb
#SBATCH --array=1%1 

# load
module load trytonp/cmdstan/2.34.1

export STAN_THREADS=true

# model name
export CMDSTAN_MODEL_NAME="mod4"
# paths
export MODEL_SRC_DIR="/users/project1/pt01268/izo/"

cd ${CMDSTAN_DIR}

# build/compile
[ -f ${MODEL_SRC_DIR}/${CMDSTAN_MODEL_NAME} ] && echo "Model " ${CMDSTAN_MODEL_NAME} " exists." || make ${MODEL_SRC_DIR}/${CMDSTAN_MODEL_NAME}

wait
