#!/bin/bash -l

#SBATCH --job-name=cmdstan_conda
#SBATCH -N 1
#SBATCH -n 48
#SBATCH -p batch
#SBATCH --time=16:00:00
#SBATCH --mem=2gb 

# load
module load trytonp/cmdstan/2.34.1

export STAN_THREADS=false

# model name
export CMDSTAN_MODEL_NAME="mod50cv"

# paths
export MODEL_SRC_DIR="/users/project1/pt01268/izo50cv"
cd ${CMDSTAN_DIR}

# build/compile
[ -f ${MODEL_SRC_DIR}/${CMDSTAN_MODEL_NAME} ] && echo "Model " ${CMDSTAN_MODEL_NAME} " exists." || make STANCFLAGS=--O1 ${MODEL_SRC_DIR}/${CMDSTAN_MODEL_NAME}

wait

cd ${MODEL_SRC_DIR}

# loop over 48 CV folds
for i in {1..48}; do
  ${MODEL_SRC_DIR}/${CMDSTAN_MODEL_NAME} sample \
    num_samples=2000 num_warmup=1000 \
    algorithm=hmc engine=nuts \
    max_depth=10 stepsize=0.01 adapt delta=0.9 \
    data file=${MODEL_SRC_DIR}/cv-data-${i}.json \
    init=${MODEL_SRC_DIR}/cv-init-${i}.json \
    output file=${MODEL_SRC_DIR}/${CMDSTAN_MODEL_NAME}-cv-${i}.csv &
done

wait