---
title: "Test plots"
author:
  - name: "Paweł Wiczling*"
    affiliations:
      - name: "Department of Biopharmaceutics and Pharmacodynamics, Medical University of Gdańsk, Gen. J. Hallera 107, 80-416 Gdańsk, Poland"
date: "`r format(Sys.Date())`"
format:
  html:
    theme: cosmo
    toc: true
    code-fold: true  
    code-tools: true
    fig-width: 7
    fig-height: 7
knitr:
  opts_chunk: 
    dev: "ragg_png"
---

# Setup


The packages we will use are listed below.

```{r setup, message=FALSE}
library(cmdstanr)
library(ggplot2)
library(gridExtra)
library(patchwork)
library(rstan)
library(tidyr)
library(dplyr)
library(posterior)
library(bayesplot)
library(GGally)
library(reshape2)
library(pracma)
library(here)
set.seed(123) 
knitr::opts_chunk$set(cache=TRUE, message=FALSE, error=FALSE, warning=FALSE, comment=NA, out.width='95%')
```


```{r test-functions}

funlogki_ls<- function(logkw, S1, S2, pKaw, alpha, R, fi, pH) {

  logkix = log(10) *(logkw - S1*(1+S2) * fi / (1 + S2 * fi));
  pHmpKa = log(10) *(pH - (pKaw + alpha * fi));
    
    if (R == 0) {
      lnki = logkix[1];
    } else if (R == 1) {
      lnki = logkix[1] +
             qgam::log1pexp(pHmpKa[1]+logkix[2]-logkix[1])-
             qgam::log1pexp(pHmpKa[1]);
    } else if (R == 2) {
      lnki = logkix[1] +
             qgam::log1pexp(pHmpKa[1]+logkix[2]-logkix[1] + 
             qgam::log1pexp(pHmpKa[2]+logkix[3]-logkix[2]))-
             qgam::log1pexp(pHmpKa[1] + 
             qgam::log1pexp(pHmpKa[2]));
    } else if (R == 3) {
      lnki = logkix[1] +
             qgam::log1pexp(pHmpKa[1]+logkix[2]-logkix[1] + 
             qgam::log1pexp(pHmpKa[2]+logkix[3]-logkix[2] +
             qgam::log1pexp(pHmpKa[3]+logkix[4]-logkix[3])))-
             qgam::log1pexp(pHmpKa[1] + 
             qgam::log1pexp(pHmpKa[2] +
             qgam::log1pexp(pHmpKa[3])));
    }
    
  logki = lnki/log(10)
  }

funlogki_ls2<- function(logkw, S1, S2, pKaw, alpha, R, fi, pH) {

  logkix = log(10) *(logkw - S1*(1+S2) * fi / (1 + S2 * fi));
  pHmpKa = log(10) *(pH - (pKaw + alpha * fi));
    
    if (R == 0) {
    lnki = logkix[1];
    } else if (R == 1) {
    lnki =   matrixStats::logSumExp(c(logkix[1],
                        logkix[2]+pHmpKa[1]))-
            matrixStats::logSumExp(c(0.0,
                        pHmpKa[1]));
    } else if (R == 2) {
    lnki =   matrixStats::logSumExp(c(logkix[1],
                        logkix[2]+pHmpKa[1],
                        logkix[3]+pHmpKa[1]+pHmpKa[2]))-
             matrixStats::logSumExp(c(0.0,
                        pHmpKa[1],
                        pHmpKa[1]+pHmpKa[2]));
    } else if (R == 3) {
    lnki =   matrixStats::logSumExp(c(logkix[1],
                        logkix[2]+pHmpKa[1],
                        logkix[3]+pHmpKa[1]+pHmpKa[2],
                        logkix[4]+pHmpKa[1]+pHmpKa[2]+pHmpKa[3]))-
             matrixStats::logSumExp(c(0.0,
                        pHmpKa[1],
                        pHmpKa[1]+pHmpKa[2],
                        pHmpKa[1]+pHmpKa[2]+pHmpKa[3]));
             
        
    }
    
  logki = lnki/log(10)
}

# analyte

logkw = c(1,0,1)
S1 =  c(4,5,4)
S2 = 2
pKaw = c(3,7)
alpha =  c(0,0) 
R =  2
fi = 0.5 
pH =  2.6

pH = seq(2,12, by=0.1)

logk<-pH %>%
  purrr::map_dbl(\(pH) funlogki_ls(logkw, S1, S2, pKaw, alpha, R, fi, pH))
logk2<-pH %>%
  purrr::map_dbl(\(pH) funlogki_ls2(logkw, S1, S2, pKaw, alpha, R, fi, pH))
plot(pH,logk)
lines(pH,logk2)
```


```{r info}
sessionInfo()
```
